services:
  db:
    image: postgres:15
    container_name: task_db
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: user_nexdom
      POSTGRES_PASSWORD: password_nexdom
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: spring_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_db

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "80:80" # O Vue ser√° acessado em http://localhost
    depends_on:
      - backend